"""empty message

Revision ID: 56998cbf44fc
Revises: 5acf8e53a6ea
Create Date: 2023-11-02 23:40:03.072708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56998cbf44fc'
down_revision = '5acf8e53a6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('liked')

    # ### end Alembic commands ###
