"""Add category_id to Post model

Revision ID: 15b5751c5684
Revises: c6b9f602ec35
Create Date: 2024-01-23 23:25:06.504245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b5751c5684'
down_revision = 'c6b9f602ec35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_cat', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_cat', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
