"""create user table

Revision ID: d4399cab4a40
Revises: 8ab5f0addef2
Create Date: 2023-12-07 16:53:18.894433

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd4399cab4a40'
down_revision = '8ab5f0addef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.alter_column('username',
                              existing_type=sa.VARCHAR(length=20),
                              type_=sa.String(length=50),
                              existing_nullable=False)
        batch_op.drop_column('password')
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=60), nullable=False))
        batch_op.alter_column('username',
                              existing_type=sa.String(length=50),
                              type_=sa.VARCHAR(length=20),
                              existing_nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
